Repository kulandaiyesum/eminence_test, pull requests merged in 2023-10, with the labels that each got.

#49 student router layout and confuiguration upadate
  src/app/login/components/login/login.component.ts
  src/app/portal-layout/portal-layout-routing.module.ts
  src/app/portal-layout/portal-layout.component.html
  src/app/portal-layout/portal-layout.component.scss
  src/app/portal-layout/portal-layout.component.ts
  src/app/registered-user/components/build-test/build-test.component.html
  src/app/registered-user/components/build-test/build-test.component.scss
  src/app/registered-user/components/build-test/build-test.component.spec.ts
  src/app/registered-user/components/build-test/build-test.component.ts
  src/app/registered-user/components/exam-room/exam-room.component.html
  src/app/registered-user/components/exam-room/exam-room.component.scss
  src/app/registered-user/components/exam-room/exam-room.component.spec.ts
  src/app/registered-user/components/exam-room/exam-room.component.ts
  src/app/registered-user/components/performance/performance.component.html
  src/app/registered-user/components/performance/performance.component.scss
  src/app/registered-user/components/performance/performance.component.spec.ts
  src/app/registered-user/components/performance/performance.component.ts
  src/app/registered-user/components/saved/saved.component.html
  src/app/registered-user/components/saved/saved.component.scss
  src/app/registered-user/components/saved/saved.component.spec.ts
  src/app/registered-user/components/saved/saved.component.ts
  src/app/registered-user/registered-user-routing.module.ts
  src/app/registered-user/registered-user.module.ts
Labels: enhancement

#50 insititute_id_params
  src/app/master/service/instituteservice.service.ts
Labels: enhancement

#54 added time out for calling get api
  src/app/faculty/components/qgen/qgen.component.ts
Labels: enhancement

#56 bug fix and improvement
  src/app/faculty/components/history/history.component.ts
  src/app/faculty/components/qgen/qgen.component.ts
  src/app/faculty/model/qgen.ts
  src/app/faculty/service/qgen.service.ts
Labels: bug

#55 edit tick mark visibility
  src/app/faculty/components/editor/editor.component.html
Labels: bug

#58 Admin modifications
  src/app/master/components/add-subscription/add-subscription.component.ts
  src/app/master/components/institution/institution.component.html
  src/app/master/components/institution/institution.component.scss
  src/app/master/components/package/package.component.html
  src/app/master/components/package/package.component.scss
  src/app/master/components/role/role.component.html
  src/app/master/components/role/role.component.scss
  src/app/master/components/subscription/subscription.component.html
  src/app/master/components/subscription/subscription.component.scss
  src/app/master/components/topic/topic.component.html
  src/app/master/components/topic/topic.component.scss
  src/app/master/components/user/user.component.html
  src/app/master/components/user/user.component.scss
Labels: bug, enhancement

#59 review pop up
  src/app/faculty/components/editor/editor.component.html
  src/app/faculty/components/editor/editor.component.ts
  src/app/faculty/service/querstion.service.ts
Labels: enhancement

#60 Qgen ky18102023
  src/app/faculty/components/qgen/qgen.component.html
  src/app/faculty/components/qgen/qgen.component.scss
  src/app/faculty/components/qgen/qgen.component.ts
  src/app/faculty/service/qgen.service.ts
Labels: bug, enhancement

#61 Review pop up logic bug resolved
  src/app/faculty/components/editor/editor.component.html
  src/app/faculty/components/editor/editor.component.scss
  src/app/faculty/components/editor/editor.component.ts
Labels: bug, enhancement

#62 Question set review all API integration
  src/app/faculty/components/editor/editor.component.html
  src/app/faculty/components/editor/editor.component.ts
  src/app/faculty/service/qgen.service.ts
Labels: bug, enhancement

#63 Complete review button
  src/app/faculty/components/editor/editor.component.html
  src/app/faculty/components/editor/editor.component.ts
  src/environments/environment.development.ts
Labels: enhancement
