Repository kulandaiyesum/eminence_test, pull requests merged in 2023-12, with the labels that each got.

#218 QGEN to exam page id bug resolved
  src/app/registered-user/components/build-test/build-test.component.html
  src/app/registered-user/components/exam/exam.component.html
  src/app/registered-user/components/exam/exam.component.ts
  src/environments/environment.development.ts
Labels: bug

#217 BUG : Sidenav open/close
  src/app/portal-layout/portal-layout.component.ts
Labels: bug

#220 Student module ky 21122023
  src/app/portal-layout/portal-layout.component.ts
  src/app/registered-user/components/calculator/calculator.component.scss
  src/app/registered-user/components/calculator/calculator.component.ts
  src/app/registered-user/components/exam-timed/exam-timed.component.html
  src/app/registered-user/components/exam-timed/exam-timed.component.scss
  src/app/registered-user/components/exam-timed/exam-timed.component.ts
  src/app/registered-user/components/exam/exam.component.html
  src/app/registered-user/components/exam/exam.component.scss
  src/app/registered-user/components/exam/exam.component.ts
  src/app/registered-user/components/notes/notes.component.scss
  src/app/registered-user/components/notes/notes.component.ts
  src/app/registered-user/registered-user.module.ts
Labels: bug, enhancement

#219 Qgen page changes
  src/app/faculty/components/qgen/qgen.component.html
  src/app/faculty/components/qgen/qgen.component.ts
Labels: bug

#221 Live exam
  src/app/registered-user/components/exam/exam.component.ts
Labels: bug

#222 Live exam
  src/app/portal-layout/components/profile/profile.component.html
  src/app/portal-layout/components/profile/profile.component.ts
Labels: bug, enhancement

#224 Register bug resolved
  src/app/login/components/register/register.component.ts
  src/app/login/service/register.service.ts
Labels: bug

#225 UPDATE: Route, config for live-examroom
  src/app/portal-layout/portal-layout.component.ts
  src/app/registered-user/components/exam-timed/exam-timed.component.scss
  src/app/registered-user/components/live-examroom/live-examroom.component.html
  src/app/registered-user/components/live-examroom/live-examroom.component.scss
  src/app/registered-user/components/live-examroom/live-examroom.component.ts
  src/environments/environment.development.ts
Labels: bug, enhancement

#226 Havenot seen API integrated
  src/app/faculty/service/qgen.service.ts
  src/app/registered-user/components/build-test/build-test.component.html
  src/app/registered-user/components/build-test/build-test.component.ts
Labels: bug

#227 Fix: Route fix and Tutor check mark update
  src/app/faculty/components/editor/editor.component.ts
  src/app/registered-user/components/exam/exam.component.html
  src/app/registered-user/components/exam/exam.component.scss
  src/app/registered-user/components/exam/exam.component.ts
Labels: bug, enhancement

#228 End date added in profile pop up
  src/app/app.module.ts
  src/app/login/components/login/login.component.html
  src/app/login/components/login/login.component.ts
  src/app/portal-layout/components/profile/profile.component.html
  src/app/portal-layout/components/profile/profile.component.ts
  src/app/portal-layout/portal-layout.module.ts
  src/app/registered-user/components/build-test/build-test.component.html
  src/app/registered-user/components/build-test/build-test.component.scss
  src/environments/environment.development.ts
Labels: bug

#229 Minor changes
  src/app/login/components/login/login.component.ts
  src/app/portal-layout/components/profile/profile.component.html
  src/app/portal-layout/components/profile/profile.component.ts
Labels: bug

#230 Live exam
  src/app/login/components/login/login.component.ts
  src/app/portal-layout/components/profile/profile.component.html
  src/app/portal-layout/components/profile/profile.component.ts
Labels: bug

#232 Highlight text ky 28122023
  src/app/registered-user/components/exam-room/exam-room.component.ts
  src/app/registered-user/components/exam-timed/exam-timed.component.html
  src/app/registered-user/components/exam-timed/exam-timed.component.scss
  src/app/registered-user/components/exam-timed/exam-timed.component.ts
  src/app/registered-user/components/live-examroom/live-examroom.component.html
  src/app/registered-user/components/live-examroom/live-examroom.component.scss
  src/app/registered-user/components/live-examroom/live-examroom.component.ts
Labels: bug, enhancement

#233 Live exam
  src/app/login/components/login/login.component.ts
  src/app/login/components/register/register.component.html
  src/app/login/components/register/register.component.ts
  src/app/login/model/register.model.ts
  src/app/portal-layout/components/profile/profile.component.html
  src/app/portal-layout/components/profile/profile.component.ts
Labels: enhancement
