Repository kulandaiyesum/eminence_test, pull requests merged in 2024-01, with the labels that each got.

#234 Register page changes
  src/app/login/components/register/register.component.html
Labels: bug

#235 Lab value as popup ky 02012024
  src/app/registered-user/components/exam-timed/exam-timed.component.html
  src/app/registered-user/components/exam-timed/exam-timed.component.scss
  src/app/registered-user/components/exam-timed/exam-timed.component.ts
  src/app/registered-user/components/exam/exam.component.html
  src/app/registered-user/components/exam/exam.component.scss
  src/app/registered-user/components/exam/exam.component.ts
  src/app/registered-user/components/lab-values/lab-values.component.scss
  src/app/registered-user/components/live-examroom/live-examroom.component.html
  src/app/registered-user/components/live-examroom/live-examroom.component.scss
  src/app/registered-user/components/live-examroom/live-examroom.component.ts
Labels: bug, enhancement, style change

#236 Forgotpassword UI update and timer added
  src/app/home/components/header/header.component.html
  src/app/home/components/header/header.component.ts
  src/app/login/components/email/email.component.html
  src/app/login/components/email/email.component.scss
  src/app/login/components/email/email.component.ts
Labels: bug, style change

#237 fix: hide resend OTP button/ timer vise versa
  src/app/login/components/email/email.component.html
Labels: bug

#238 Package Added for role(STUDENT)
  src/app/master/components/add-subscription/add-subscription.component.ts
  src/app/master/components/user/user.component.html
  src/app/master/components/user/user.component.ts
Labels: bug

#241 Validation changes
  src/app/login/components/register/register.component.html
  src/app/master/components/institute-popup/institute-popup.component.html
  src/app/master/components/package-popup/package-popup.component.html
Labels: bug, enhancement

#240 style: UI update for email verification page
  src/app/login/components/verify-email/verify-email.component.html
  src/app/login/components/verify-email/verify-email.component.scss
  src/assets/images/email.png
Labels: style change

#242 User type bug resolved
  src/app/master/components/institute-popup/institute-popup.component.html
  src/app/master/components/package-popup/package-popup.component.html
  src/app/master/components/subscription/subscription.component.html
Labels: bug, enhancement

#243 feat: view information component added
  src/app/master/components/institution/institution.component.html
  src/app/master/components/institution/institution.component.ts
  src/app/master/components/view-information/view-information.component.html
  src/app/master/components/view-information/view-information.component.scss
  src/app/master/components/view-information/view-information.component.spec.ts
  src/app/master/components/view-information/view-information.component.ts
  src/app/master/master.module.ts
Labels: enhancement

#245 style: UI change in update attribute component
  src/app/master/components/add-attributes/add-attributes.component.ts
Labels: style change

#244 Success message added for payment success
  src/app/login/components/register/register.component.ts
Labels: bug, enhancement

#246 Feat: Add view user component
  src/app/master/components/institution/institution.component.ts
  src/app/master/components/user/user.component.html
  src/app/master/components/user/user.component.scss
  src/app/master/components/user/user.component.ts
  src/app/master/components/view-institution/view-institution.component.html
  src/app/master/components/view-institution/view-institution.component.scss
  src/app/master/components/view-institution/view-institution.component.spec.ts
  src/app/master/components/view-institution/view-institution.component.ts
  src/app/master/components/view-user/view-user.component.html
  src/app/master/components/view-user/view-user.component.scss
  src/app/master/components/view-user/view-user.component.spec.ts
  src/app/master/components/view-user/view-user.component.ts
  src/app/master/master.module.ts
Labels: enhancement
